### ISSUE TITLE
bytearray taking too slow to pass

### ISSUE THREAD

**Issue by IshitaChristian** [PavelPutin/mathematical-logic-and-theory-of-algorithms#2]
Hello,

I am trying to pass my byte array from java to python using python as a server but, this is taking too long. the time of a method which passes the array from java to python is too long. Can you provide me a better solution?

Thanks

**Comment by PavelPutin** [comment]
Hello, Ishita,

It's the studying project and I have no plans to develop it in future. So I can't provide you a better solution. I think, you can find a better solution than this one.

Thanks for pointing out the problem!
